Display Last Captured Image
srobo/kit-ui pull request #231
Opened 2022-12-30 20:32 UTC by sedders123

Works in conjunction with https://github.com/srobo/sr-robot3/pull/90 to provide users with the ability to see the last image their robot captured

2023-01-02 17:37 UTC, WillB97 approved these changes
Looks good
![Web UI demo](https://user-images.githubusercontent.com/10937272/210107371-f0ef9aff-4838-43cb-acb2-a954948b1aaf.png)

2023-01-03 19:31 UTC, trickeydan requested changes, later dismissed

2023-01-03 19:31 UTC, trickeydan commented on src/main.js
> +  }
This feels a bit nasty. Can we do it conditionally based on the topic? e.g a list of raw topics that we don't attempt to parse as json? Or maybe even topics that don't begin with `astoria/`

2023-01-03 20:05 UTC, trickeydan commented on src/main.js
> +  }
I've pushed [6ae33d5](https://github.com/srobo/kit-ui/pull/231/commits/6ae33d594529ccb074cf75774742c6c8d251a7f8) to resolve this.

2023-01-03 20:07 UTC, WillB97 approved these changes

2023-01-03 20:08 UTC, merged